version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.11"

x-default-dev-volumes: &default_dev_volumes
  volumes:
    - ./backend:/app
    - ./backend/db.sqlite3:/tmp/db.sqlite3

services:
  dev:
    build:
      context: ./backend
      target: development
      args:
        <<: *build_args
    image: "fast-adv-development"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    <<: *default_dev_volumes

  prod:
    build:
      context: ./backend
      target: production
      args:
        <<: *build_args
    image: "fast-adv-production"
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "fast_adv"
      POSTGRES_PASSWORD: "fast_adv"
      POSTGRES_DB: "fast_adv"
