version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.11"

x-default-volumes: &default_volumes
  volumes:
    - ./:/api
    - ./dev.db:/tmp/dev.db

services:
  dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "my_api-development"
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    <<: *default_volumes

  prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "my_api-production"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: 'INFO'
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fast_adv

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080