# fly.toml app configuration file generated for fast-adv-api on 2023-11-04T20:54:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fast-adv-api"
primary_region = "gru"

[build]

[build.args]
  INSTALL_PYTHON_VERSION="3.11"

[deploy]
  strategy = "rolling"
  max_unavailable = 1.0
  release_command = "task migrate"

[env]
  ALGORITHM='HS256'
  ACCESS_TOKEN_EXPIRE_MINUTES=30
  SMTP_TLS='False'
  SMTP_PORT=25
  SMTP_HOST='localhost'
  SMTP_USER=''
  SERVER_HOST='https://fast-adv-api.fly.dev/api/v1/'
  PROJECT_NAME='Fast-ADV'
  EMAILS_FROM_EMAIL="ro-reply@turque.com.br"
  EMAILS_ENABLED='True'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
