# fly.toml app configuration file generated for fast-adv-api on 2023-11-04T20:54:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fast-adv-api"
primary_region = "gru"

[build]

[build.args]
  INSTALL_PYTHON_VERSION="3.11"

[deploy]
  strategy = "rolling"
  max_unavailable = 1.0

[env]
  ACCESS_TOKEN_EXPIRE_MINUTES = "30"
  ALGORITHM = "HS256"
  DATABASE_URL = "postgres://postgres:Ce4JsQsPX6X7NPg@fast-adv-backend-db.flycast:5432"
  SECRET_KEY = "your-secret-key"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
