"""alter invite table

Revision ID: 1ac276ff7ed1
Revises: ee2144b3d377
Create Date: 2023-10-24 23:00:41.168693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac276ff7ed1'
down_revision: Union[str, None] = 'ee2144b3d377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('token', sa.String(), nullable=False))
    op.add_column('invites', sa.Column('name', sa.String(), nullable=False))
    op.add_column('invites', sa.Column('email', sa.String(), nullable=False))
    op.add_column('invites', sa.Column('team', sa.Integer(), nullable=False))
    op.add_column('invites', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('invites', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('invites', 'invite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('invite', sa.VARCHAR(), nullable=False))
    op.drop_column('invites', 'sent_at')
    op.drop_column('invites', 'create_at')
    op.drop_column('invites', 'team')
    op.drop_column('invites', 'email')
    op.drop_column('invites', 'name')
    op.drop_column('invites', 'token')
    # ### end Alembic commands ###
