"""DDD: Change context User to Athlete

Revision ID: 7b66bf1fd170
Revises: d10c4341c8a2
Create Date: 2024-04-24 15:32:30.063082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b66bf1fd170'
down_revision: Union[str, None] = 'd10c4341c8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_email'), 'athlete', ['email'], unique=True)
    op.create_index(op.f('ix_athlete_id'), 'athlete', ['id'], unique=False)
    op.create_index(op.f('ix_athlete_name'), 'athlete', ['name'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_table('user')
    op.add_column('equipamentsathlete', sa.Column('athlete_id', sa.Integer(), nullable=False))
    op.drop_constraint('equipamentsathlete_user_id_fkey', 'equipamentsathlete', type_='foreignkey')
    op.create_foreign_key(None, 'equipamentsathlete', 'athlete', ['athlete_id'], ['id'])
    op.drop_column('equipamentsathlete', 'user_id')
    op.add_column('invite', sa.Column('athlete_id', sa.Integer(), nullable=False))
    op.drop_constraint('invite_user_id_fkey', 'invite', type_='foreignkey')
    op.create_foreign_key(None, 'invite', 'athlete', ['athlete_id'], ['id'])
    op.drop_column('invite', 'user_id')
    op.add_column('race', sa.Column('athlete_id', sa.Integer(), nullable=False))
    op.drop_constraint('race_user_id_fkey', 'race', type_='foreignkey')
    op.create_foreign_key(None, 'race', 'athlete', ['athlete_id'], ['id'])
    op.drop_column('race', 'user_id')
    op.add_column('strategicplanning', sa.Column('athlete_id', sa.Integer(), nullable=False))
    op.drop_constraint('strategicplanning_user_id_fkey', 'strategicplanning', type_='foreignkey')
    op.create_foreign_key(None, 'strategicplanning', 'athlete', ['athlete_id'], ['id'])
    op.drop_column('strategicplanning', 'user_id')
    op.drop_constraint('team_owner_id_fkey', 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'athlete', ['owner_id'], ['id'])
    op.add_column('teamrace', sa.Column('athlete_id', sa.Integer(), nullable=False))
    op.drop_constraint('teamrace_user_id_fkey', 'teamrace', type_='foreignkey')
    op.create_foreign_key(None, 'teamrace', 'athlete', ['athlete_id'], ['id'])
    op.drop_column('teamrace', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teamrace', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teamrace', type_='foreignkey')
    op.create_foreign_key('teamrace_user_id_fkey', 'teamrace', 'user', ['user_id'], ['id'])
    op.drop_column('teamrace', 'athlete_id')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_owner_id_fkey', 'team', 'user', ['owner_id'], ['id'])
    op.add_column('strategicplanning', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'strategicplanning', type_='foreignkey')
    op.create_foreign_key('strategicplanning_user_id_fkey', 'strategicplanning', 'user', ['user_id'], ['id'])
    op.drop_column('strategicplanning', 'athlete_id')
    op.add_column('race', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.create_foreign_key('race_user_id_fkey', 'race', 'user', ['user_id'], ['id'])
    op.drop_column('race', 'athlete_id')
    op.add_column('invite', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invite', type_='foreignkey')
    op.create_foreign_key('invite_user_id_fkey', 'invite', 'user', ['user_id'], ['id'])
    op.drop_column('invite', 'athlete_id')
    op.add_column('equipamentsathlete', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'equipamentsathlete', type_='foreignkey')
    op.create_foreign_key('equipamentsathlete_user_id_fkey', 'equipamentsathlete', 'user', ['user_id'], ['id'])
    op.drop_column('equipamentsathlete', 'athlete_id')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_athlete_name'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_id'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_email'), table_name='athlete')
    op.drop_table('athlete')
    # ### end Alembic commands ###
