"""Recriação base

Revision ID: 842b7ff8a16c
Revises: 
Create Date: 2024-05-17 12:28:40.442489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842b7ff8a16c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_email'), 'athlete', ['email'], unique=True)
    op.create_index(op.f('ix_athlete_id'), 'athlete', ['id'], unique=False)
    op.create_index(op.f('ix_athlete_name'), 'athlete', ['name'], unique=False)
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_id'), 'invite', ['id'], unique=False)
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('race_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('url_race', sa.String(), nullable=True),
    sa.Column('race_description', sa.String(), nullable=True),
    sa.Column('place_description', sa.String(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_id'), 'race', ['id'], unique=False)
    op.create_table('equipaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('modality', sa.Enum('bike', 'kayak', 'trek', 'rope', 'first_aid', name='modalityenun'), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipaments_id'), 'equipaments', ['id'], unique=False)
    op.create_table('fugleman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fugleman_email'), 'fugleman', ['email'], unique=False)
    op.create_index(op.f('ix_fugleman_id'), 'fugleman', ['id'], unique=False)
    op.create_index(op.f('ix_fugleman_name'), 'fugleman', ['name'], unique=False)
    op.create_table('strategicplanning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission', sa.String(), nullable=True),
    sa.Column('vision', sa.String(), nullable=True),
    sa.Column('values', sa.String(), nullable=True),
    sa.Column('strategic_objectives', sa.String(), nullable=True),
    sa.Column('immediate_objectives', sa.String(), nullable=True),
    sa.Column('strengths', sa.String(), nullable=True),
    sa.Column('weaknesses', sa.String(), nullable=True),
    sa.Column('opportunities', sa.String(), nullable=True),
    sa.Column('threats', sa.String(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategicplanning_id'), 'strategicplanning', ['id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_members', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_table('teamrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teamrace_id'), 'teamrace', ['id'], unique=False)
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('estimated_time', sa.Time(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('previous_stage', sa.Integer(), nullable=True),
    sa.Column('next_stage', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['next_stage'], ['timeline.id'], ),
    sa.ForeignKeyConstraint(['previous_stage'], ['timeline.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_id'), 'timeline', ['id'], unique=False)
    op.create_table('equipamentsathlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observations', sa.String(), nullable=False),
    sa.Column('have', sa.Boolean(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('equipament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['equipament_id'], ['equipaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentsathlete_id'), 'equipamentsathlete', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipamentsathlete_id'), table_name='equipamentsathlete')
    op.drop_table('equipamentsathlete')
    op.drop_index(op.f('ix_timeline_id'), table_name='timeline')
    op.drop_table('timeline')
    op.drop_index(op.f('ix_teamrace_id'), table_name='teamrace')
    op.drop_table('teamrace')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_strategicplanning_id'), table_name='strategicplanning')
    op.drop_table('strategicplanning')
    op.drop_index(op.f('ix_fugleman_name'), table_name='fugleman')
    op.drop_index(op.f('ix_fugleman_id'), table_name='fugleman')
    op.drop_index(op.f('ix_fugleman_email'), table_name='fugleman')
    op.drop_table('fugleman')
    op.drop_index(op.f('ix_equipaments_id'), table_name='equipaments')
    op.drop_table('equipaments')
    op.drop_index(op.f('ix_race_id'), table_name='race')
    op.drop_table('race')
    op.drop_index(op.f('ix_invite_id'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_athlete_name'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_id'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_email'), table_name='athlete')
    op.drop_table('athlete')
    # ### end Alembic commands ###
