"""models fix

Revision ID: d10c4341c8a2
Revises: fc61d2dd5b13
Create Date: 2023-12-27 15:52:04.826737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10c4341c8a2'
down_revision: Union[str, None] = 'fc61d2dd5b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('team_id', sa.Integer(), nullable=False))
    op.add_column('invite', sa.Column('race_id', sa.Integer(), nullable=False))
    op.drop_column('invite', 'team')
    op.drop_column('invite', 'race')
    op.alter_column('timeline', 'previous_stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('timeline', 'next_stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline', 'next_stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('timeline', 'previous_stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('invite', sa.Column('race', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invite', sa.Column('team', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('invite', 'race_id')
    op.drop_column('invite', 'team_id')
    # ### end Alembic commands ###
