"""models rebase

Revision ID: d3fcbf022635
Revises: dbe4fab30879
Create Date: 2023-12-26 15:40:55.763945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3fcbf022635'
down_revision: Union[str, None] = 'dbe4fab30879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('modality', sa.Enum('bike', 'kayak', 'trek', 'rope', 'first_aid', name='modalityenun'), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipaments_id'), 'equipaments', ['id'], unique=False)
    op.create_table('fugleman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fugleman_email'), 'fugleman', ['email'], unique=False)
    op.create_index(op.f('ix_fugleman_id'), 'fugleman', ['id'], unique=False)
    op.create_index(op.f('ix_fugleman_name'), 'fugleman', ['name'], unique=False)
    op.create_table('teamrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teamrace_id'), 'teamrace', ['id'], unique=False)
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.Enum('bike', 'kayak', 'trek', 'rope', 'first_aid', name='modalityenun'), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_id'), 'timeline', ['id'], unique=False)
    op.create_table('equipamentsathlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observations', sa.String(), nullable=False),
    sa.Column('have', sa.Boolean(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipament_id'], ['equipaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentsathlete_id'), 'equipamentsathlete', ['id'], unique=False)
    op.add_column('team', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('team', sa.Column('race_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team', 'race', ['race_id'], ['id'])
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'is_admin')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'race_id')
    op.drop_column('team', 'logo')
    op.drop_index(op.f('ix_equipamentsathlete_id'), table_name='equipamentsathlete')
    op.drop_table('equipamentsathlete')
    op.drop_index(op.f('ix_timeline_id'), table_name='timeline')
    op.drop_table('timeline')
    op.drop_index(op.f('ix_teamrace_id'), table_name='teamrace')
    op.drop_table('teamrace')
    op.drop_index(op.f('ix_fugleman_name'), table_name='fugleman')
    op.drop_index(op.f('ix_fugleman_id'), table_name='fugleman')
    op.drop_index(op.f('ix_fugleman_email'), table_name='fugleman')
    op.drop_table('fugleman')
    op.drop_index(op.f('ix_equipaments_id'), table_name='equipaments')
    op.drop_table('equipaments')
    # ### end Alembic commands ###
