"""Create strategic planning table

Revision ID: dbe4fab30879
Revises: fa295c5b81e4
Create Date: 2023-11-30 17:45:26.102247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe4fab30879'
down_revision: Union[str, None] = 'fa295c5b81e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategicplanning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission', sa.String(), nullable=True),
    sa.Column('vision', sa.String(), nullable=True),
    sa.Column('values', sa.String(), nullable=True),
    sa.Column('strategic_objectives', sa.String(), nullable=True),
    sa.Column('immediate_objectives', sa.String(), nullable=True),
    sa.Column('strengths', sa.String(), nullable=True),
    sa.Column('weaknesses', sa.String(), nullable=True),
    sa.Column('opportunities', sa.String(), nullable=True),
    sa.Column('threats', sa.String(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategicplanning_id'), 'strategicplanning', ['id'], unique=False)
    op.add_column('invite', sa.Column('race', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite', 'race')
    op.drop_index(op.f('ix_strategicplanning_id'), table_name='strategicplanning')
    op.drop_table('strategicplanning')
    # ### end Alembic commands ###
