"""timeline adjust

Revision ID: fc61d2dd5b13
Revises: d3fcbf022635
Create Date: 2023-12-27 13:02:17.102526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc61d2dd5b13'
down_revision: Union[str, None] = 'd3fcbf022635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('stage', sa.String(), nullable=False))
    op.add_column('timeline', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('timeline', sa.Column('estimated_time', sa.Time(), nullable=True))
    op.add_column('timeline', sa.Column('observations', sa.String(), nullable=True))
    op.add_column('timeline', sa.Column('previous_stage', sa.Integer(), nullable=False))
    op.add_column('timeline', sa.Column('next_stage', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'timeline', 'timeline', ['next_stage'], ['id'])
    op.create_foreign_key(None, 'timeline', 'timeline', ['previous_stage'], ['id'])
    op.drop_column('timeline', 'modality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('modality', postgresql.ENUM('bike', 'kayak', 'trek', 'rope', 'first_aid', name='modalityenun'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_column('timeline', 'next_stage')
    op.drop_column('timeline', 'previous_stage')
    op.drop_column('timeline', 'observations')
    op.drop_column('timeline', 'estimated_time')
    op.drop_column('timeline', 'distance')
    op.drop_column('timeline', 'stage')
    # ### end Alembic commands ###
