import { getUserById } from '../services/get-user-by-id';
import { getUsers } from '../services/get-users';


export const metadata = {
    title: 'Usuário - Minha Aventura!',
    description: 'Generated by create next app',
}

export async function generateStaticParams() {
    const users = await getUsers();
    const usersIds = users.map((user) => ({ userId: user.id.toString() }));

    return usersIds;
}

export default async function UserDetailsPage({
    params,
}: {
    params: { userId: string };
}) {
    const user = await getUserById(params.userId);

    return (
        <>
            <h2>
                Usuário: {user.first_name} {user.last_name}
            </h2>
            <span>{user.email}</span>
            <hr />
            {user.body}
            <hr />
            {user.avatar}
            <hr />
        </>
    );
}