import '../globals.css'
import Image from 'next/image'
import me from '../../public/img/bg.jpg'
 
function Bg() {
  return (
    <Image
      src={me}
      alt="Picture of the author"
      sizes="100vw"
      style={{
        width: '100%',
        height: 'auto',
      }}
    />
  )
}


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='Bg'>
        {children}
      </body>
    </html>
  )
}
